### ISSUE TITLE
EMIPGenerator can't find TextMeshProFonts by name in Meakashi and Tsumihoroboshi

### ISSUE THREAD

**Issue by enumag** [07th-mod/ui-editing-scripts#1]
When I compile the assets everything seems to work fine in the question arcs but in answer arcs fonts are completely [broken](https://cdn.discordapp.com/attachments/384427950478589972/493417364000342046/config.png).

Maybe I'm doing something wrong but I don't think so since question arcs are fine.

The bug applies to both msgothic_0 and msgothic_2. Any idea what could have gone wrong?

**Comment by TellowKrinkle** [comment]
I'm guessing the issue is actually with EMIPGenerator, it doesn't properly find TextMeshProFont assets by name on Meakashi and Tsumihoroboshi, which causes it to not include them in the emip file.  For now you can just put numbers on them to get them to work but I should try to get name lookup working later.

**Comment by enumag** [comment]
@tellowkrinkle If it couldn't find the fonts then why are they broken? I mean if they were not found then they would not be replaced, right?

**Comment by TellowKrinkle** [comment]
The atlas files got replaced but the files with information about the characters in the atlas didn't, leading to the breakage

**Comment by enumag** [comment]
Ah ok, that explains it. Well we don't need to have the script working any time soon so I'll just wait until you fix the EMIPGenerator. Take your time with it, school has far more priority, ok?

**Comment by TellowKrinkle** [comment]
Should be fixed by 4c25c182d0346b68f56c7cdd20fa7fd196e0cc9c, could you make sure?

**Comment by enumag** [comment]
Thanks, I'll test it when I get home.

**Comment by enumag** [comment]
Yeah, it works fine now. Thank you!
