### ISSUE TITLE
ERROR: Can't find 7zip as '7z' or '7za'

### ISSUE THREAD

**Issue by FurudeRick** [07th-mod/ui-editing-scripts#19]
I want to translate rei but when i run  `python build.py`  show `ERROR: Can't find 7zip as '7z' or '7za'.``
I don't know what to do.
I have already run pip install -r requirements.txt. 
python version 3.8

**Comment by FurudeRick** [comment]
![QQ截图20240205163349](https://github.com/07th-mod/ui-editing-scripts/assets/49405432/559fa188-2e9c-45e5-b06f-5cd2606cb8f2)

**Comment by enumag** [comment]
Install 7zip and make sure it can be found in PATH.

**Comment by drojf** [comment]
@enumag I decided to just make the build.py script download 7zip if it is missing in https://github.com/07th-mod/ui-editing-scripts/commit/f9057f64ad0b04a8c49b51f55c7b5f22d2749837

also am discussing with them in discord

@FurudeRick let me know if it works and I'll close this issue

**Comment by FurudeRick** [comment]
@drojf It has been resolved。I always thought it was necessary to put a 7z file in the current folder,😂
