### ISSUE TITLE
Fix chapter preview in answer arcs

### ISSUE THREAD

**Issue by enumag** [07th-mod/ui-editing-scripts#2]
(PSD is in the ui-edits directory in dropbox)

This is the PNG our UI is currently using:

![ChapterPreview_Kai](https://user-images.githubusercontent.com/539462/55665203-69a13c80-583b-11e9-8732-c55e2bc67bbd.png)

For consistency with question arcs we need to have the red and blue swapped.

Another issue is that the positioning is 1-2px off in some cases. Here is the same image from vanilla to give you a better understanding for what the positions should be:

![ChapterPreview-sharedassets0 assets-21](https://user-images.githubusercontent.com/539462/55665259-69ee0780-583c-11e9-9ad4-bb5b9e91df93.png)

Finally all lines that currently have the red background have their *text* moved from the correct position by 1px to the right. Move these labels back left by one 1px.

Note: I can't open PSDs to save as PNG so when you're done please give me a PNG.

**Comment by Grelo** [comment]
Done.
