### ISSUE TITLE
Regarding fonts

### ISSUE THREAD

**Issue by Leticiel** [07th-mod/ui-editing-scripts#21]
May I ask how to generate and change SDF fonts, since TextMeshPro is no longer available in the Unity 5.5.5 Asset Store?

**Comment by drojf** [comment]
Yea...this has been an issue for a while now but I hadn't looked into it (I will ask the translation teams on discord to see if anyone had backed it up or knows how to get it working)

However, are you sure you need to generate SDF fonts? Which language do you need to generate fonts for?

We have a pre-generated font which supports many languages which you might be able to use.

**Comment by Leticiel** [comment]
Thanks for your answer.
Yeah, the pre-generated SDF fonts does support my language, but I want to generate them myself so I can pick the font I like.

**Comment by drojf** [comment]
@staciaa123 A member of the Korean translation team sent me both Unity 5.5.5f1 and Text Mesh Pro for 5.5.5f1

See download link and included Readme.md on how to install: <https://1drv.ms/f/s!Ar-lAVeetlqhhf01Us28Zbo3TNvdow?e=2rWbiE>

**Please let me know if it works.** Initially I tried using the included plugin on an older version of Unity 5.4.1f1and it didn't work. So I'm not 100% sure if I fixed it by using the correct version of unity, or if I fixed it coincidentally when messing around with things.

Also, please don't close this issue yet, I want to make note of this in our Wiki (and possibly

**Comment by Leticiel** [comment]
The plugin works like a charm with Unity 5.5.5f1. Thank you so much!

**Comment by drojf** [comment]
Updated wiki with this download link, also mirrored Unity 2019.4 in case that ever goes down, see https://github.com/07th-mod/wiki/commit/f0c8f18d4c096b4c57b32f889919e78cfb2a3310
