### ISSUE TITLE
Config screen improvements

### ISSUE THREAD

**Issue by enumag** [07th-mod/ui-editing-scripts#3]
(PSD is in the ui-edits directory in dropbox)

Here is the current config screen:

![configbg](https://user-images.githubusercontent.com/539462/55665293-247e0a00-583d-11e9-83c4-c963e3ba6bde.png)

Some of these texts need to be changed:

`TEXT BOX TRANSPARENCY` => `TEXTBOX OPACITY`
`BGM VOLUME` => `MUSIC VOLUME`
`SOUND VOLUME` => `SOUND EFFECTS VOLUME`

For the japanese version we need some changes as well:

TEXTBOX OPACITY  `メツセ一ジウインドウ透明度` => `メツセ一ジウインドウ不透明度`
MUSIC VOLUME  `BGM音量` => `音楽 音量`

Note: the PSD also contains a version where the stripes are gray. We want them red.

Note: I can't open PSDs to save as PNG so when you're done please give me a PNG.

**Comment by Grelo** [comment]
Done.
