### ISSUE TITLE
FIx position of japanese close button on config screen

### ISSUE THREAD

**Issue by enumag** [07th-mod/ui-editing-scripts#4]
(PSD is in the ui-edits directory in dropbox, it's named "saveloadhigurashi")

Move the highlighted button down by 1 pixel.

![saveloadhigurashi](https://user-images.githubusercontent.com/539462/55665528-bdaf1f80-5841-11e9-871c-315f206267d1.png)

Note: I can't open PSDs to save as PNG so when you're done please give me a PNG.

**Comment by Grelo** [comment]
Done.
