### ISSUE TITLE
Fix buttons and arrows for Tsumihoroboshi

### ISSUE THREAD

**Issue by enumag** [07th-mod/ui-editing-scripts#5]
(There is no PSD for this one, work with the PNGs I post here.

This is the current image from Tsumihotoboshi:

![TipsPrefab](https://user-images.githubusercontent.com/539462/55665560-48901a00-5842-11e9-90f7-769eaaf6a0bd.png)

The buttons and arrows need to be changed to match those from Meakashi:

![TipsPrefab](https://user-images.githubusercontent.com/539462/55665573-81c88a00-5842-11e9-839a-390440ad6343.png)

In this iteration you don't need to do anything about the thumbnails. I have a suspicion that the image contains extra thumbnails from Meakashi and not all of them are actually used in the actual game.

**Comment by Grelo** [comment]
Done.
