### ISSUE TITLE
Fix save & load screen

### ISSUE THREAD

**Issue by enumag** [07th-mod/ui-editing-scripts#6]
(PSD is in the ui-edits directory in dropbox, it's named "saveloadbg")

Here is the current save & load screen:

![saveloadbg](https://user-images.githubusercontent.com/539462/55665636-af620300-5843-11e9-9e5e-c7829039395a.png)

After the next DLL update there will be no save button for the quick saves at the bottom. They are saved using a shortcut and the button is not working anyway. With only a load button it doesn't make sense to have the labels say `Quick Save/Load FILE`. I somehow don't like `Quick Load` either because such slots are most often called quick saves. So in my opinion we should change the labels to `Quick Save 1/2/3` (FILE seems unnecessary too) but if you have another suggestions let me know.

Note: I can't open PSDs to save as PNG so when you're done please give me a PNG.

**Comment by enumag** [comment]
Solved by Grelo.

![obrazek](https://user-images.githubusercontent.com/539462/55667387-f78d1f80-585b-11e9-957f-7fe708529581.png)

**Comment by Grelo** [comment]
Done.
