### ISSUE TITLE
In-game menu improvements

### ISSUE THREAD

**Issue by enumag** [07th-mod/ui-editing-scripts#7]
(PSD is in the ui-edits directory in dropbox, it's either "HigurashiMenu.psd" or "HigurashiMenu_Size Edit.psd", not sure)

Current PNG:

![HigurashiMenu](https://user-images.githubusercontent.com/539462/55669874-059f6800-587d-11e9-8581-66892edc664a.png)

The text on some of these lines is not centered vertically. See for example "RETURN TO TIPS" and "EXIT TO MENU" (but that's not all).

For consistency, change "HIDE TEXT BOX" to "HIDE TEXTBOX".

I'm also considering changing the border of all red buttons from black to white for consistency with the rest of the UI. This is an experiment though so better make a backup of the PSD before doing this.

Note: The buttons with black text and red background don't seem to be used in the game so you can skip those.

Note: I can't open PSDs to save as PNG so when you're done please give me a PNG.

**Comment by Grelo** [comment]
Done.
