### ISSUE TITLE
Matsuribayashi missing from vanilla UI archive

### ISSUE THREAD

**Issue by drojf** [07th-mod/ui-editing-scripts#9]
The vanilla UI archive is missing the matsuribayashi files: http://07th-mod.com/archive/vanilla.7z

Note that the Linux GOG/Mangagamer UI file is different to the Linux Steam UI file, despite having the same unity version - in the past I needed to generate a new patched UI file based on the GOG/Mangagamer UI file, see this issue: https://github.com/07th-mod/matsuribayashi/issues/32

You can download that base UI file with from here: https://github.com/07th-mod/matsuribayashi/issues/32#issuecomment-725988634

It should have SHA256: A200EC2A85349BC03B59C8E2F106B99ED0CBAAA25FC50928BB8BA2E2AA90FCE9 (downloaded on 2020-11-12)

**Comment by enumag** [comment]
Can you update the vanilla.7z to add all the missing files? Are there some files you don't have available yourself?

**Comment by enumag** [comment]
I don't think the repo currently allows multiple versions with the same OS and Unity version based on the platform (Steam/MG/GOG) though. If neither of them can be used with the other version then I guess we should update the library to allow this. :-/

**Comment by drojf** [comment]
> Can you update the vanilla.7z to add all the missing files?

ah yea I can upload the ones that I have - I wasn't sure if there was something special I had to do, or if you already had them on your computer and just didn't upload them

> ...I guess we should update the library...

I can look at this at some point, but I mainly brought up this issue to keep track of it, rather than it being urgent/needed for somethign, so not sure when I'll get to doing it.

**Comment by drojf** [comment]
I've now updated the vanilla archive: https://07th-mod.com/archive/vanilla.7z (should be about 215 megabytes, sometimes it takes a while to update)

I've added anything I saw missing. Some archives are listed as needed in the compileall.sh but actually aren't needed (not used by my installer), so I didn't add them. I also added some notes in a text file for the .assets that I added so that its' easier to keep track of the different versions.

I changed the folder structure slightly to `assets/vanilla` instead of just `vanilla` so that you can just extract it at the root of the repository.

I've been messing with both adding a script and/or making github actions be able to build the UI scripts more easily (for translators and for us), hence why I updated the archive. I'll make a PR with these changes at some point. That's happening in this repository: https://github.com/drojf/ui-editing-scripts

The folder with a CRC32 checksum is due to the issue we had where two incompatible sharedassets existed with the same unity version/os version. That is handled in the above forked repo but not yet merged to this repo.
